# Test Features/Functions
This is a temp notebook to test out functions and features required for the DECONVersation package. Using a step by step guide on how a user would use this package. <br>
<b> Note </b>: This might be converted to a tutorial upon package deployment

# Step 0: Prep Data

In [1]:
# For reading and processing pseudobulk
from pseudobulk import *

# For pre-processing h5ad for geneformer or cell2sentence
from preprocessing import *

In [2]:
# Path to pseudobulk
# Contains two samples that are essentially duplicates (pre-menopausal)
path_1 = "/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/single_cell_refs/CZI04N_post_menopausal_sequence_duplicates.h5ad"

# Contains single cell data from a single sample with batch effects (post-menopausal)
path_2 = "/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/single_cell_refs/CZI041N_pre_menopausal.h5ad"

### For Geneformer

In [3]:
import scanpy as sc
# Read the h5ad file (just to explore columns and variables)
adata_1 = sc.read_h5ad(path_1)

# Prep data for geneformer (first data set)
adata_1_gf = adata_1.copy()

# Get ensembl ID
adata_1_gf.var.index = gene_id_name_map(gene_list=adata_1_gf.var.index,
                                      mode="to_symbol" )
# Remove unmapped genes
adata_1_gf = adata_1_gf[:, adata_1_gf.var.index.notnull()]

# Prep data
adata_1_gf = load_and_prep_data(adata= adata_1_gf, 
                              cell_type_col= "heca_lineage", 
                              mode="geneformer")

/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv/src/DECONVersation/preprocessing.py:49: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata.obs["cell_id"] = adata.obs.index

In [4]:
# Read the h5ad file (just to explore columns and variables)
adata_2 = sc.read_h5ad(path_2)

# Prep data for geneformer (first data set)
adata_2_gf = adata_2.copy()

# Get ensembl ID
adata_2_gf.var.index = gene_id_name_map(gene_list=adata_2_gf.var.index,
                                      mode="to_symbol" )
# Remove unmapped genes
adata_2_gf = adata_2_gf[:, adata_2_gf.var.index.notnull()]

# Prep data
adata_2_gf = load_and_prep_data(adata= adata_2_gf, 
                              cell_type_col= "heca_lineage", 
                              mode="geneformer")

/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv/src/DECONVersation/preprocessing.py:49: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata.obs["cell_id"] = adata.obs.index

### For Cell2Sentence

In [5]:
# Prep data for geneformer (first data set)
adata_1_c2s = adata_1.copy()

# Prep data for Cell2Sentence
adata_1_c2s = load_and_prep_data(adata = adata_1_c2s,
                                 cell_type_col = "heca_lineage", 
                                 mode = "c2s",
                                 organism = "Homo Sapiens")

In [6]:
# Prep data for geneformer (first data set)
adata_2_c2s = adata_2.copy()

# Prep data
adata_2_c2s = load_and_prep_data(adata = adata_2_c2s, 
                              cell_type_col = "heca_lineage", 
                              mode = "c2s",
                              organism = "Homo Sapiens")

# Step 1: Create Pseudobulk

### For Geneformer

In [7]:
# For h5ad containing two different samples (duplicates)
all_pseudobulks = []
all_cell_props = []

id_list = adata_1_gf.obs['id'].unique() #since there two sample IDs here

for sample_id in id_list:
    adata_subset = adata_1_gf[adata_1_gf.obs["id"] == sample_id].copy()

    pseudobulk_temp, pseudobulk_cell_prop_temp = generate_pseudobulk(
        adata = adata_subset,
        cell_type_col = "heca_lineage",
    )

    # Optional (added sample names for easier tracking)
    pseudobulk_temp.index = [f"{sample_id}_PB_{i+1}" for i in range(0, len(pseudobulk_temp))]
    pseudobulk_cell_prop_temp.index = [f"{sample_id}_PB_{i+1}" for i in range(0, len(pseudobulk_temp))]

    all_pseudobulks.append(pseudobulk_temp)
    all_cell_props.append(pseudobulk_cell_prop_temp)

# Concatenate all results
pseudo_bulk_gf_1 = pd.concat(all_pseudobulks, axis=0, ignore_index=False)
cell_prop_1 = pd.concat(all_cell_props, axis=0, ignore_index=False)

In [8]:
#For reference containing just a sample with batch effects 
pseudo_bulk_gf_2, cell_prop_2 = generate_pseudobulk(adata = adata_2_gf,
                                       cell_type_col = "heca_lineage")

pseudo_bulk_gf_2.index = [f'{adata_2_gf.obs["id"].unique()[0]}_PB_{i+1}' for i in range(0, len(pseudo_bulk_gf_2))]
cell_prop_2.index = [f'{adata_2_gf.obs["id"].unique()[0]}_PB_{i+1}' for i in range(0, len(cell_prop_2))]

In [9]:
# Combine pseudobulk
pseudobulk_all = pd.concat([pseudo_bulk_gf_1, pseudo_bulk_gf_2], axis=0, ignore_index=False)
cell_prop_all = pd.concat([cell_prop_1, cell_prop_2], axis=0, ignore_index=False)

### For Cell2Sentence

In [10]:
# Convert using coverting coverting function
pseudobulk_all_c2s = pseudobulk_all.copy()
pseudobulk_all_c2s.columns = gene_id_name_map(gene_list = pseudobulk_all.columns,
                                      mode = "to_ensembl")

# Step 2: Create Signature Matrix

In [11]:
sig_mat_gf = create_signature_matrix(adata = adata_1_gf,
                                     sample_col = "id", # sample id column
                                     sample_ids = ["B4P4-CZI04N", "B4P1-CZI04N"],
                                     celltype_col = "heca_lineage",
                                     celltypes = ["Endothelial", "Mesenchymal", "Epithelial"],
                                     groupby = "heca_lineage",
                                     output_path = None)

/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv/src/DECONVersation/preprocessing.py:241: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  signature = expr.groupby(groupby).mean().T

In [12]:
sig_mat_c2s = create_signature_matrix(adata = adata_1_c2s,
                                     sample_col = "id", # sample id column
                                     sample_ids = ["B4P4-CZI04N", "B4P1-CZI04N"],
                                     celltype_col = "heca_lineage",
                                     celltypes = ["Endothelial", "Mesenchymal", "Epithelial"],
                                     groupby = "heca_lineage",
                                     output_path = None)

/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv/src/DECONVersation/preprocessing.py:241: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  signature = expr.groupby(groupby).mean().T

# Step 4: Extract Geneformer Embeddings

In [13]:
from embeddings import *

In [14]:
sig_mat_c2s_embed = extract_embs(
    bulk_df = sig_mat_gf.T,
    mode = "geneformer",
    temp_output_dir = "/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/", 
    model_path= "ctheodoris/Geneformer",
    delete_temp_files = True
)

Pseudobulk AnnData saved to: /gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/gf_tokens.h5ad
Starting Geneformer tokenization...
Tokenizing /gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/gf_tokens.h5ad

100%|██████████| 1/1 [00:00<00:00,  8.94it/s]
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/anndata/_core/anndata.py:747: UserWarning:
AnnData expects .obs.index to contain strings, but got values like:
    ['Endothelial', 'Epithelial', 'Mesenchymal']

    Inferred to be: categorical

  value_idx = self._prep_dim_index(value.index, attr)
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/anndata/_core/anndata.py:796: ImplicitModificationWarning: Trying to modify index of attribute `.obs` of view, initializing view as actual.
  getattr(self, attr).index = value
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/geneformer/tokenizer.py:473: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for i in adata.var["ensembl_id_collapsed"][coding_miRNA_loc]
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/geneformer/tokenizer.py:476: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coding_miRNA_ids = adata.var["ensembl_id_collapsed"][coding_miRNA_loc]

/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/gf_tokens.h5ad has no column attribute 'filter_pass'; tokenizing all cells.
Creating dataset.
Loading Geneformer model...

BertForMaskedLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:774: UserWarning: `return_dict_in_generate` is NOT set to `True`, but `output_hidden_states` is. When `return_dict_in_generate` is not `True`, `output_hidden_states` is ignored.
  warnings.warn(
CLS token present in token dictionary, excluding from average.
EOS token present in token dictionary, excluding from average.

Loading tokenized dataset...
Extracting Geneformer embeddings...

  0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
pb_gf_embed = extract_embs(
    bulk_df = pseudobulk_all,
    mode = "geneformer",
    temp_output_dir = "/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/", 
    model_path= "ctheodoris/Geneformer",
    delete_temp_files = True
)

Pseudobulk AnnData saved to: /gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/gf_tokens.h5ad
Starting Geneformer tokenization...
Tokenizing /gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/gf_tokens.h5ad

100%|██████████| 6/6 [00:06<00:00,  1.06s/it]
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/anndata/_core/anndata.py:796: ImplicitModificationWarning: Trying to modify index of attribute `.obs` of view, initializing view as actual.
  getattr(self, attr).index = value
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/geneformer/tokenizer.py:473: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for i in adata.var["ensembl_id_collapsed"][coding_miRNA_loc]
/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/geneformer/tokenizer.py:476: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coding_miRNA_ids = adata.var["ensembl_id_collapsed"][coding_miRNA_loc]

/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/gf_tokens.h5ad has no column attribute 'filter_pass'; tokenizing all cells.
Creating dataset.
Loading Geneformer model...

/nfs/sw/easybuild/software/custom-conda/geneformer-1.0/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:774: UserWarning: `return_dict_in_generate` is NOT set to `True`, but `output_hidden_states` is. When `return_dict_in_generate` is not `True`, `output_hidden_states` is ignored.
  warnings.warn(
CLS token present in token dictionary, excluding from average.
EOS token present in token dictionary, excluding from average.

Loading tokenized dataset...
Extracting Geneformer embeddings...

  0%|          | 0/60 [00:00<?, ?it/s]

# Step 5: Extract Cell2Sentence Embeddings

In [ ]:
sig_mat_c2s_embed = extract_embs(
    bulk_df = sig_mat_gf.T,
    mode = "c2s",
    temp_output_dir = "/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/DECONVersation/", 
    model_path= "/gpfs/commons/groups/compbio/projects/rf_projects/deconv_data/deconvbench/c2s/410mmouse/2026-02-08-08_41_26_finetune_cell_type_prediction/checkpoint-9090",
    delete_temp_files = False
)

<b> Features to add or fix </b> <br> 
Add chunk size or batch size for both c2s and geneformer <br>
Possibly split geneformer and c2s into different functions without using a wrapper <br>
For geneformer, expose user to select which embedding dimension and type (cls vs cell) to extarct <br>
For cell2sentence, expose user to how many input dimensions to match

# Step 6: Run NNLS

In [17]:
from deconvolution import *

In [18]:
pb_gf_embed.columns = "GF_" + pb_gf_embed.columns.astype(str) #Add this to the function

In [19]:
sig_mat_c2s_embed.columns = "GF_" + sig_mat_c2s_embed.columns.astype(str) #Add this to the function

In [26]:
cell_prop_pred = run_deconv_nnls(
    bulk_df = pb_gf_embed.T,
    signature_df = sig_mat_c2s_embed.T,
    normalize = True)

Using 1152 common features.
Running NNLS deconvolution...

# Step 7: Evaluate

In [25]:
from evaluation import *

In [35]:
rmse_per_cell_type = compute_rmse(true_df = cell_prop_all,
                                 pred_df = cell_prop_pred,
                                 return_per_celltype = True)

rmse_per_cell_type = pd.DataFrame(rmse_per_cell_type)

In [37]:
rmse_per_cell_type

              overall  per_celltype
Endothelial  0.071457      0.042378
Mesenchymal  0.071457      0.082325
Epithelial   0.071457      0.082129

In [40]:
corr_per_cell_type = compute_correlation(true_df = cell_prop_all,
                                         pred_df = cell_prop_pred,
                                        return_per_celltype = True)

corr_per_cell_type = pd.DataFrame(corr_per_cell_type)

In [41]:
corr_per_cell_type

             overall  per_celltype
Endothelial  0.95557      0.977834
Mesenchymal  0.95557      0.973379
Epithelial   0.95557      0.985247